GET http://localhost:8080/welcome
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwYWkiLCJleHAiOjE3MDEzNjU4MjIsImlhdCI6MTcwMTM0NzgyMn0.sQFIHz1Fw3QqDjV3Y90QywLFz3zt3z-LMiXAc-PMu0myfPKkNa6XQJZt-ZlAuyuVIDfc1jcaysAJ2hSmHvkVhg